include: package:lint/analysis_options.yaml

#linter:
#  rules:
    # ------ Disable individual rules ----- #
    #                 ---                   #
    # Turn off what you don't like.         #
    # ------------------------------------- #

    # Use parameter order as in json response
    #always_put_required_named_parameters_first: false